# Generated by Django 4.0.5 on 2022-07-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_usuario_is_staff_alter_usuario_is_studet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='usuario/', verbose_name='Imagen de prefil'),
        ),
    ]
