# Generated by Django 4.0.5 on 2022-06-19 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de categoria')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_gravedad', models.IntegerField(choices=[(1, 'Muy bajo'), (2, 'Bajo'), (3, 'Moderado'), (4, 'Alto'), (5, 'Muy alto')], verbose_name='Nivel de gravedad')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='Elemento_deportivo/Categorias/', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elementos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Elemento_deportivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(unique=True, verbose_name='Numero identificador')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='Elemento_deportivo/Elementos/', verbose_name='Imagen')),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='Estado de sisponibilidad')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elementos.estadoelemento')),
                ('sub_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elementos.subcategoria')),
            ],
            options={
                'verbose_name': 'Elemento deportivo',
                'verbose_name_plural': 'Elementos Deportivos',
            },
        ),
    ]
