# Generated by Django 4.0.5 on 2022-06-19 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elemento_deportivo',
            new_name='ElementoDeportivo',
        ),
    ]
