# Generated by Django 4.0.5 on 2022-06-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0005_alter_prestamo_fecha_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(verbose_name='Fecha de prestamo'),
        ),
    ]
