# Generated by Django 4.0.5 on 2022-06-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0007_remove_prestamo_hora_prestamo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id_estudiante',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Id del estudiante'),
        ),
    ]
