# Generated by Django 4.0.5 on 2022-06-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0008_remove_prestamo_estudiante_prestamo_id_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(verbose_name='Fecha de prestamo'),
        ),
    ]
