# Generated by Django 4.0.5 on 2022-06-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0009_alter_prestamo_fecha_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='hora_presamto',
            field=models.IntegerField(choices=[(1, '12:12PM'), (2, '03:30PM')], default=1, verbose_name='Hora Prestamo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(verbose_name='Fecha de prestamo'),
        ),
    ]
