# Generated by Django 4.0.5 on 2022-06-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0013_remove_prestamo_id_estudiante_prestamo_estudiante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
