# Generated by Django 4.0.5 on 2022-06-20 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Elementos', '0014_delete_prestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(verbose_name='Fecha de prestamo')),
                ('hora_presamto', models.IntegerField(choices=[(1, '12:12PM'), (2, '03:30PM')], verbose_name='Hora Prestamo')),
                ('elemento_deportivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elementos.elementodeportivo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
            },
        ),
    ]
