# Generated by Django 4.0.5 on 2022-06-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0016_prestamo_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='id_estudiante',
            field=models.PositiveIntegerField(default=1, verbose_name='Id del estudiante'),
            preserve_default=False,
        ),
    ]
