# Generated by Django 4.0.5 on 2022-07-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0018_elementodeportivo_estado_eliminacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementodeportivo',
            name='disponibilidad',
            field=models.BooleanField(default=True, verbose_name='Estado de disponibilidad'),
        ),
        migrations.AlterField(
            model_name='elementodeportivo',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='Elementos/', verbose_name='Imagen'),
        ),
    ]
