# Generated by Django 4.0.5 on 2022-07-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0020_alter_elementodeportivo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementodeportivo',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='Elementos/', verbose_name='Imagen'),
        ),
    ]
