# Generated by Django 4.0.5 on 2022-07-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0025_alter_prestamo_fecha_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='id_estudiante',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Id del estudiante'),
        ),
    ]
