# Generated by Django 4.0.5 on 2022-07-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0026_alter_prestamo_id_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creacion prestamo'),
        ),
    ]
