# Generated by Django 4.0.5 on 2022-07-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0027_alter_prestamo_fecha_prestamo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TextField(max_length=50, verbose_name='Hora')),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='Estado de disponibilidad')),
            ],
            options={
                'verbose_name': 'hora',
                'verbose_name_plural': 'horas',
            },
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='hora_presamto',
            field=models.TextField(verbose_name='Hora Prestamo'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='id_estudiante',
            field=models.PositiveIntegerField(verbose_name='Id del estudiante'),
        ),
        migrations.AddField(
            model_name='elementodeportivo',
            name='horas_disponibles',
            field=models.ManyToManyField(to='Elementos.horasdisponible'),
        ),
    ]
