# Generated by Django 4.0.5 on 2022-07-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0028_horasdisponible_alter_prestamo_hora_presamto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementodeportivo',
            name='horas_disponibles',
        ),
        migrations.AddField(
            model_name='elementodeportivo',
            name='hora_presamto',
            field=models.IntegerField(choices=[(1, '12:00PM - 12:30PM'), (2, '03:00PM - 03:30PM')], default=2, verbose_name='Hora Prestamo'),
            preserve_default=False,
        ),
    ]
