# Generated by Django 4.0.5 on 2022-07-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0030_remove_elementodeportivo_hora_presamto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='estado',
        ),
    ]
