# Generated by Django 4.0.5 on 2022-07-05 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Elementos', '0031_remove_prestamo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='id_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
