# Generated by Django 4.0.5 on 2022-07-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0034_prestamo_devolucion_alter_prestamo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementodeportivo',
            name='cantidad',
            field=models.SmallIntegerField(default=2, verbose_name='Cantidad de prestamos diarios'),
        ),
    ]
