# Generated by Django 4.0.5 on 2022-07-05 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0037_remove_elementodeportivo_hora_presamto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementodeportivo',
            name='horas_disponibles',
        ),
        migrations.AddField(
            model_name='elementodeportivo',
            name='horas_disponibles',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Elementos.horasdisponible'),
            preserve_default=False,
        ),
    ]
