# Generated by Django 4.0.5 on 2022-07-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0038_remove_elementodeportivo_horas_disponibles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementodeportivo',
            name='horas_disponibles',
        ),
        migrations.AddField(
            model_name='elementodeportivo',
            name='horas_disponibles',
            field=models.ManyToManyField(to='Elementos.horasdisponible'),
        ),
    ]
