# Generated by Django 4.0.5 on 2022-07-05 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Elementos', '0039_remove_elementodeportivo_horas_disponibles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_devolucion', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de devolucion')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='Elementos/devolucion/', verbose_name='Imagen')),
                ('encarcago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estado_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elementos.estadoelemento')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Elementos.prestamo')),
            ],
        ),
    ]
