# Generated by Django 4.0.5 on 2022-07-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0041_prestamo_cancelacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolu',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='cancelacion',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cancelar prestamo '),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='devolucion',
            field=models.BooleanField(default=False, verbose_name='Devolucion'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Aceptar prestamo'),
        ),
    ]
