# Generated by Django 4.0.5 on 2022-07-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0042_remove_devolu_imagen_alter_prestamo_cancelacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementodeportivo',
            options={},
        ),
    ]
