# Generated by Django 4.0.5 on 2022-07-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0043_alter_elementodeportivo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolu',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='Elementos/devolucion/', verbose_name='Imagen'),
        ),
    ]
