# Generated by Django 4.0.5 on 2022-07-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Elementos', '0044_devolu_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devolu',
            old_name='imagen',
            new_name='imagen_estado',
        ),
    ]
